// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20240520212456_reserve tickets")]
    partial class reservetickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actors = "Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr., Alden Ehrenreich",
                            AgeRestriction = 16,
                            Description = "Oppenheimer is a 2023 epic biographical thriller drama film written, directed, and produced by Christopher Nolan. It follows the life of J. Robert Oppenheimer, the American theoretical physicist who helped develop the first nuclear weapons during World War II.",
                            Genre = "Biography, Drama, History",
                            Rating = "8.3",
                            ReleaseDate = new DateTime(2023, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oppenheimer",
                            Trailer = "https://www.youtube.com/watch?v=uYPbbksJxIg&ab_channel=UniversalPictures"
                        },
                        new
                        {
                            Id = 2,
                            Actors = "Margot Robbie, Ryan Gosling, Issa Rae, Kate McKinnon, Alexandra Shipp, Emma Mackey",
                            AgeRestriction = 12,
                            Description = "Set in the colorful Barbie Land, stereotypical Barbie lives a perfect life every single day. One day, she shows signs of being...a human. She decides to go to the Real World to find the cure in order to make herself perfect again.",
                            Genre = "Adventure, Comedy, Fantasy",
                            Rating = "6.8",
                            ReleaseDate = new DateTime(2023, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Barbie",
                            Trailer = "https://www.youtube.com/watch?v=Kb7jYOYXiVc&ab_channel=RapidTrailer"
                        },
                        new
                        {
                            Id = 3,
                            Actors = "timothee Chalamet, Zendaya, Rebecca Ferguson, Javier Dardem, Josh Brollin, Austin Butler",
                            AgeRestriction = 16,
                            Description = "Dune: Part Two will explore the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
                            Genre = "Action, Adventure, Drama, Sci-Fi",
                            Rating = "8.6",
                            ReleaseDate = new DateTime(2024, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dune: Part Two",
                            Trailer = "https://www.youtube.com/watch?v=Way9Dexny3w&ab_channel=WarnerBros.Pictures"
                        },
                        new
                        {
                            Id = 4,
                            Actors = "Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy, Brett Cullen",
                            AgeRestriction = 16,
                            Description = "The film, loosely based on DC Comics characters, stars Joaquin Phoenix as the Joker. Set in 1981, it follows Arthur Fleck, a failed clown and aspiring stand-up comedian whose descent into mental illness and nihilism inspires a violent countercultural revolution against the wealthy in a decaying Gotham City.",
                            Genre = "Crime, Drama, Thriller",
                            Rating = "8.4",
                            ReleaseDate = new DateTime(2019, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Joker",
                            Trailer = "https://www.youtube.com/watch?v=t433PEQGErc&ab_channel=WarnerBros.Pictures"
                        },
                        new
                        {
                            Id = 5,
                            Actors = "Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon, Jon Favreau, Willem Dafoe",
                            AgeRestriction = 12,
                            Description = "Peter Parker's secret identity is revealed to the entire world. Desperate for help, Peter turns to Doctor Strange to make the world forget that he is Spider-Man. The spell goes horribly wrong and shatters the multiverse, bringing in monstrous villains that could destroy the world.",
                            Genre = "Action, Adventure, Fantasy, Sci-Fi",
                            Rating = "8.2",
                            ReleaseDate = new DateTime(2021, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spider-Man: No Way Home",
                            Trailer = "https://www.youtube.com/watch?v=JfVOs4VSpmA&ab_channel=SonyPicturesEntertainment"
                        },
                        new
                        {
                            Id = 6,
                            Actors = "Tom Hardy, Charlize Theron, Nicholas Hoult, Zoe Kravitz, Hugh Keays-Byrne, Josh Helman",
                            AgeRestriction = 16,
                            Description = "Set in a post-apocalyptic desert wasteland where petrol and water are scarce commodities, Fury Road follows Max Rockatansky (Hardy), who joins forces with Imperator Furiosa (Theron) against cult leader Immortan Joe (Keays-Byrne) and his army, leading to a lengthy road battle.",
                            Genre = "Action, Adventure, Sci-Fi, THriller",
                            Rating = "8.1",
                            ReleaseDate = new DateTime(2015, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mad Max: Fury Road",
                            Trailer = "https://www.youtube.com/watch?v=hEJnMQG9ev8&ab_channel=WarnerBros.Pictures"
                        },
                        new
                        {
                            Id = 7,
                            Actors = "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Tom Holland, Benedict Cumberbatch, Chadwick Boseman, Paul Rudd",
                            AgeRestriction = 12,
                            Description = "AVENGERS: ENDGAME is set after Thanos' catastrophic use of the Infinity Stones randomly wiped out half of Earth's population in Avengers: Infinity War. Those left behind are desperate to do something -- anything -- to bring back their lost loved ones",
                            Genre = "Action, Adventure, Drama, Sci-Fi",
                            Rating = "8.4",
                            ReleaseDate = new DateTime(2019, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avengers: Endgame",
                            Trailer = "https://www.youtube.com/watch?v=hA6hldpSTF8&ab_channel=MarvelEntertainment"
                        },
                        new
                        {
                            Id = 8,
                            Actors = "Rebecca Hall, Brian Tyree Henry, Dan Stevens, Kaylee Hottle, Alex Ferns, Fala Chen",
                            AgeRestriction = 12,
                            Description = "The new installment in the Monsterverse puts the mighty Kong and the fearsome Godzilla against a colossal deadly threat hidden within our world that threatens the existence of their species and our very own, as well as diving deep into the mysteries of Skull Island and beyond.",
                            Genre = "Action, Adventure, Fantasy, Sci-Fi, Thriller",
                            Rating = "6.3",
                            ReleaseDate = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Godzilla x Kong: The New Empire",
                            Trailer = "https://www.youtube.com/watch?v=lV1OOlGwExM&ab_channel=WarnerBros.Pictures"
                        },
                        new
                        {
                            Id = 9,
                            Actors = "Anne Hathaway, Nicholas Galitzine, Ella Rubin, Annie Mumolo, Perry Mattfeld, Reid Scott",
                            AgeRestriction = 16,
                            Description = "Based on the acclaimed, contemporary love story of the same name, The Idea of You centers on Solène (Anne Hathaway), a 40-year-old single mom who begins an unexpected romance with 24-year-old Hayes Campbell (Nicholas Galitzine), the lead singer of August Moon, the hottest boy band on the planet.",
                            Genre = "Comedy, Drama, Romance",
                            Rating = "6.4",
                            ReleaseDate = new DateTime(2024, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The idea of you",
                            Trailer = "https://www.youtube.com/watch?v=V8i6PB0gGOA&ab_channel=PrimeVideo"
                        },
                        new
                        {
                            Id = 10,
                            Actors = "Jim Carrey, Ed Harris, Laura Linney, Noah Emmerich, Natascha McElhore, Holland Taylor",
                            AgeRestriction = 12,
                            Description = "An insurance salesman discovers his whole life is actually a reality TV show.",
                            Genre = "Drama, Comedy",
                            Rating = "8.2",
                            ReleaseDate = new DateTime(1998, 6, 5, 13, 35, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Truman Show",
                            Trailer = "https://www.youtube.com/watch?v=dlnmQbPGuls"
                        },
                        new
                        {
                            Id = 11,
                            Actors = "Robert Downey Jr, Gwyneth Paltrow, Terrence Howard, Jeff Bridges, Leslie Bibb, Shaun Toub",
                            AgeRestriction = 16,
                            Description = "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
                            Genre = "Adventure, Action, Ski-Fi",
                            Rating = "7.9",
                            ReleaseDate = new DateTime(2008, 5, 1, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Man",
                            Trailer = "https://www.youtube.com/watch?v=8ugaeA-nMTc"
                        },
                        new
                        {
                            Id = 12,
                            Actors = "Chris Evans, Hugo Weaving, Samuel L Jackson, Hayley Atwell, Stanley Tucci, Sebastian Stan",
                            AgeRestriction = 16,
                            Description = "Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a Super-Soldier serum .But being Captain America comes at a price as he attempts to take down a warmonger and a terrorist organization.",
                            Genre = "Ski-Fi, Adventure, Action",
                            Rating = "6.9",
                            ReleaseDate = new DateTime(2011, 7, 22, 18, 35, 0, 0, DateTimeKind.Unspecified),
                            Title = "Captain America: The First Avenger",
                            Trailer = "https://www.youtube.com/watch?v=JerVrbLldXw"
                        },
                        new
                        {
                            Id = 13,
                            Actors = "Juliete Binoche, Johnny Deep, Judi Dench, Alfred Molina, Antonio Gil, Ron Cook, Lena Olin, John Wood",
                            AgeRestriction = 18,
                            Description = "A French woman and her young daughter open up a chocolate shop in a small remote village that shakes up the rigid morality of the community.",
                            Genre = "Drama, Romance",
                            Rating = "7.2",
                            ReleaseDate = new DateTime(2001, 1, 19, 4, 10, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chocolat",
                            Trailer = "https://www.youtube.com/watch?v=692hOJq1KJE"
                        },
                        new
                        {
                            Id = 14,
                            Actors = "Johnny Deep, Freddie Highmore, David Kelly, Helena Bonham Carter, Noah Taylor, Missi Pyle, James Fox, Adam Godley, Julia Winter",
                            AgeRestriction = 12,
                            Description = "Charlie, a young boy from an impoverished family, and four other kids win a tour of an amazing chocolate factory run by an imaginative chocolatier, Willy Wonka, and his staff of Oompa-Loompas.",
                            Genre = "Adventure, Comedy, Musical, Family, Fantasy",
                            Rating = "6.7",
                            ReleaseDate = new DateTime(2005, 7, 15, 20, 5, 0, 0, DateTimeKind.Unspecified),
                            Title = "Charlie and the Chocolate Factory",
                            Trailer = "https://www.youtube.com/watch?v=OFVGCUIXJls"
                        },
                        new
                        {
                            Id = 15,
                            Actors = "Johnny Deep, Leonardo DiCaprio, Juliette Lewis, Mary Steenburgen, Darlene Cates, Laura Harrington, Kevin Tighe, Marry Kate Schellhardt, Cameron Finley, Crispin Glover",
                            AgeRestriction = 18,
                            Description = "A young man in a small Midwestern town struggles to care for his mentally-disabled younger brother and morbidly obese mother while attempting to pursue his own happiness.",
                            Genre = "Drama",
                            Rating = "7.7",
                            ReleaseDate = new DateTime(1994, 3, 4, 13, 50, 0, 0, DateTimeKind.Unspecified),
                            Title = "What's Eating Gilbert Grape",
                            Trailer = "https://www.youtube.com/watch?v=nCsVjQaNV0E"
                        },
                        new
                        {
                            Id = 16,
                            Actors = "Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates, Frances Fisher, Gloria Stuart, Bill Paxton, David Warner, Victor Garber, Bernard Hill, Suzy Amis",
                            AgeRestriction = 18,
                            Description = "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
                            Genre = "Romance, Drama",
                            Rating = "7.9",
                            ReleaseDate = new DateTime(1997, 12, 19, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic",
                            Trailer = "https://www.youtube.com/watch?v=I7c1etV7D7g"
                        },
                        new
                        {
                            Id = 17,
                            Actors = "Marisa Abela, Eddie Marsan, Lesley Manville, Juliet Cowan, Anna Darvas, Harley Bird, Thelma Ruby",
                            AgeRestriction = 16,
                            Description = "The life and music of Amy Winehouse, through the journey of adolescence to adulthood and the creation of one of the best-selling albums of our time.",
                            Genre = "Biography",
                            Rating = "6.6",
                            ReleaseDate = new DateTime(2024, 5, 17, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Title = "Back To Black",
                            Trailer = "https://www.youtube.com/watch?v=rYzIOBwyhIU"
                        },
                        new
                        {
                            Id = 18,
                            Actors = "Kirsten Dunst, Wagner Moura, Cailee Spaeny, Nick Offerman, Jefferson White, Evan Nai",
                            AgeRestriction = 18,
                            Description = "A journey across a dystopian future America, following a team of military-embedded journalists as they race against time to reach DC before rebel factions descend upon the White House.",
                            Genre = "Adventure, Action",
                            Rating = "7.6",
                            ReleaseDate = new DateTime(2024, 5, 19, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Civil War",
                            Trailer = "https://www.youtube.com/watch?v=rYzIOBwyhIU"
                        },
                        new
                        {
                            Id = 19,
                            Actors = "Cailey Fleming, Ryan Reynolds, john Krasinski, Fiona Shaw, Stewe Carell, Alan Kim, Phoebe Waller-Bridge",
                            AgeRestriction = 10,
                            Description = "A young girl who goes through a difficult experience begins to see everyone's imaginary friends who have been left behind as their real-life friends have grown up.",
                            Genre = "Family, Comedy, Drama",
                            Rating = "7.4",
                            ReleaseDate = new DateTime(2024, 5, 16, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Title = "IF",
                            Trailer = "https://www.youtube.com/watch?v=ss2KvK-w6w8"
                        });
                });

            modelBuilder.Entity("Core.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NormalPlaces")
                        .HasColumnType("int");

                    b.Property<int>("VipPlaces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "first room",
                            NormalPlaces = 50,
                            VipPlaces = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "second room",
                            NormalPlaces = 30,
                            VipPlaces = 5
                        });
                });

            modelBuilder.Entity("Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FilmId")
                        .HasColumnType("int");

                    b.Property<decimal>("NormalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NormalReserved")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<decimal>("VipPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VipReserved")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.HasIndex("RoomId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2024, 5, 17, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 1,
                            NormalPrice = 8.00m,
                            NormalReserved = 0,
                            RoomId = 1,
                            VipPrice = 10.00m,
                            VipReserved = 0
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2024, 5, 18, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            FilmId = 2,
                            NormalPrice = 10.00m,
                            NormalReserved = 0,
                            RoomId = 2,
                            VipPrice = 12.00m,
                            VipReserved = 0
                        });
                });

            modelBuilder.Entity("Core.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NumberOfTickets")
                        .HasColumnType("int");

                    b.Property<int>("SeatType")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Session", b =>
                {
                    b.HasOne("Core.Entities.Film", "Film")
                        .WithMany("Sessions")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Core.Entities.Ticket", b =>
                {
                    b.HasOne("Core.Entities.Session", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Film", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Core.Entities.Room", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Core.Entities.Session", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
